urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from userprofile.forms import PasswordResetForm

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('userprofile.views',
    url(r'^account/img/(?P<userkey>[.a-zA-Z0-9_\-]+)/(?P<filename>.*)$', 'avatar_image', name='avatar_image'),
    url(r'^account/conf/$', 'user_settings', name='user_settings'),
    url(r'^account/avatar/$', 'user_avatar', name='user_avatar'),
    url(r'^account/theme/$', 'user_theme', name='user_theme'),
    url(r'^account/bg/(?P<userkey>[.a-zA-Z0-9_\-]+)/(?P<filename>.*)$', 'theme_image', name='theme_image'),
    url(r'^account/links/$', 'user_link', name='user_link'),
    url(r'^account/link/(?P<link_key>[.a-zA-Z0-9_\-]+)/remove/$', 'link_remove', name='user_linkremove'),
    url(r'^account/admin/$', 'user_admin', name='user_admin'),
    url(r'^account/admin/(?P<username>[.a-zA-Z0-9_@\-]+)/$', 'user_admin_detail', name='user_admin_detail'),
)

urlpatterns += patterns('',
    url(r'^account/login/$', 'userprofile.views.email_login', {'template_name': 'userprofile/login.html'}, name='login'),
    url(r'^account/logout/$', 'userprofile.views.do_logout', name='logout'),
    url(r'^account/register/$', 'userprofile.views.register_inactive_user', name='register'),
    url(r'^account/register/complete/$', direct_to_template, {'template': 'userprofile/register_complete.html'}, name='register_complete'),
    url(r'^account/activate/complete/$', 'userprofile.views.activate_complete', name='register_activate_complete'),
    url(r'^account/activate/(?P<activation_key>\w+)/$', 'userprofile.views.activate', name='register_activate'),
    url(r'^account/password/change/$', 'django.contrib.auth.views.password_change', 
        {'template_name':'userprofile/password_change_form.html'}, name='user_pass_change'),
    url(r'^account/password/change/complete/$', 'django.contrib.auth.views.password_change_done', 
        {'template_name':'userprofile/password_change_done.html'}, name='user_pass_change_done'),
    url(r'^account/recover/$', 'django.contrib.auth.views.password_reset', 
            {'template_name':'userprofile/getpassword.html', 'email_template_name':'userprofile/password_reset_email.html',
             'password_reset_form':PasswordResetForm}, name='password_reset'),
    url(r'^account/recover/complete/$', 'django.contrib.auth.views.password_reset_done', 
            {'template_name': 'userprofile/password_reset_done.html'}, name='reset_done'),
    url(r'^account/confirm/(?P<uidb36>.+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', 
            {'template_name': 'userprofile/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^account/confirm/complete/$', 'django.contrib.auth.views.password_reset_complete', 
            {'template_name': 'userprofile/password_reset_complete.html'}, name='password_reset_last'),
)

urlpatterns += patterns('walkon.views',
    url(r'^on/(?P<username>[.a-zA-Z0-9_@\-]+)/$','userpage', name='userpage'),
    url(r'^cfg/$','global_config', name='cfg_main'),
    url(r'^cfg/goal/$','goal', name='cfg_goal'),
    url(r'^cfg/activities/$','activities', name='cfg_activities'),
)

#Initializations 

urlpatterns += patterns('walkon.views',
    url(r'^getsteptable/$', 'get_step_table', name='step_table_ajax'),
    url(r'^getfullstepform/$', 'get_full_step_form', name='full_step_form_ajax'),
    url(r'^reports/$', 'reports', name='reports'),
    url(r'^reports/fullresults/$', 'full_results', name='full_results'),
    url(r'^reports/map/$', 'reports', name='report_map'),
    url(r'^reports/activities/$', 'reports_activities', name='report_activities'),
    url(r'^reports/benchmark/$', 'reports_benchmark', name='report_benchmark'),
    url(r'^reports/projections/$', 'reports_projections', name='report_projections'),
    url(r'^reports/rankings/$', 'reports_rankings', name='report_rankings'),
    url(r'^reports/steps/$', 'reports_steps', name='report_steps'),
    url(r'^bg/(?P<filename>.*)$', 'global_theme_image', name='global_theme_image'),
    (r'^updatestats$', 'update_user_stats'),
    (r'^cropstats$', 'crop_stats'),
    (r'^clearstats$', 'clear_stats'),
    (r'^clearsteps$', 'clear_steps'),
    (r'^fillconfig$', 'create_config'),
    (r'^init$', 'initialization'),    
    url(r'^$', 'index', name="index"),
    (r'^admin/(.*)', admin.site.root),
)

userprofile/models.py
import re
import sha
import random
from datetime import datetime, timedelta
from google.appengine.ext import db
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _
import settings
from userprofile import utils
from ragendja.auth.models import User as RjUser

def init_avatar():
    from google.appengine.api.urlfetch import fetch
    d = fetch('%s/img/default_avatar_large.jpg' % settings.DOMAIN_URL)
    avatar = Avatar(image=d.content, status='public',filename='default_avatar_large.jpg')
    avatar.put()
    return avatar

class Theme(db.Model):
    name = db.StringProperty()
    bg_image_path = db.StringProperty()
    thumbnail_path = db.StringProperty()
    bg_color = db.StringProperty()
    bg_repeat = db.BooleanProperty()
    site_color1 = db.StringProperty()
    site_color2 = db.StringProperty()
    link_color = db.StringProperty()
    
    def get_bg_url(self):
        return self.bg_image_path
        
class Avatar(db.Model):
    status = db.StringProperty(choices=set(['public','private']), default='private')
    image = db.BlobProperty(default=None)
    filename = db.StringProperty()

    @classmethod
    def get_default_avatar(cls):
        avatar = Avatar.all().filter('status =','public').get()
        if not avatar:
            avatar = init_avatar()
        return avatar

class User(RjUser):
    display_name = db.StringProperty()
    bio = db.TextProperty()
    avatar = db.Reference(Avatar)
    location = db.StringProperty()
    theme = db.Reference(Theme)
    bg_name = db.StringProperty()
    bg_color = db.StringProperty()
    bg_repeat = db.BooleanProperty()
    site_color1 = db.StringProperty()
    site_color2 = db.StringProperty()
    link_color = db.StringProperty()
    
    def __init__(self, *args, **kwargs):
        super(User, self).__init__(*args, **kwargs)
        from walkon.models import GlobalConfig
        self.GCONFIG = GlobalConfig.all().get()

    def get_absolute_url(self):
        return reverse('userpage', kwargs={'username': self.username})
    
    def is_anonymous(self):
        "Always returns False. This is a way of comparing User objects to anonymous users."
        return False

    def get_display_name(self):
        return self.display_name or self.username
    
    def get_full_name(self):
        return self.get_display_name()
            
    def get_bgimage(self):
        "return the user, theme or default background image"
        if self.bg_name:
            return reverse('theme_image', kw_args={'userkey': self.key, 'filename':self.bg_name})
        elif self.theme:
            return self.theme.bg_image_path
        elif self.GCONFIG.theme:
            return self.GCONFIG.theme.bg_image_path
        elif self.GCONFIG.bg_name:
            return reverse('global_theme_image', kw_args={'filename':self.GCONFIG.bg_name})
        else:
            return None

    def get_bgcolor(self):
        "returns the user background color or the default background color"
        return self.get_theme_field('bg_color')
    
    def get_bgrepeat(self):
        return self.get_theme_field('bg_repeat')

    def get_linkcolor(self):
        return self.get_theme_field('link_color')

    def get_sitecolor1(self):
        return self.get_theme_field('site_color1')

    def get_sitecolor2(self):
        return self.get_theme_field('site_color2')
         
    def get_theme_field(self, fieldname):
        if getattr(self, fieldname):
            return getattr(self, fieldname)
        elif self.theme:
            return getattr(self.theme, fieldname)
        elif getattr(self.GCONFIG, fieldname):
            return getattr(self.GCONFIG, fieldname)
        elif self.GCONFIG.theme:
            return getattr(self.GCONFIG.theme, fieldname)
        else:
            return None
    
    def put(self):
        if not self.avatar:
            self.avatar = Avatar.get_default_avatar()
        super(User,self).put()


class BgImage(db.Model):
    """
    Background image for user theme customization 
    """
    user = db.Reference(User, required=True)
    filename = db.StringProperty()
    image = db.BlobProperty(default=None)
    
    
class Link(db.Model):
    """
    Links for user profile page
    """
    user = db.Reference(User, required=True)
    name = db.StringProperty(required=True)
    url = db.LinkProperty(required=True)
    logo = db.StringProperty()
    
    def put(self):
        self.logo = utils.find_link_logo(self.url)
        super(Link,self).put()

#From appenginepatch sample app

SHA1_RE = re.compile('^[a-f0-9]{40}$')

class RegistrationManager(models.Manager):

    def activate_user(self, activation_key):
        """
        Validate an activation key and activate the corresponding
        ``User`` if valid.        
        """
        # Make sure the key we're trying conforms to the pattern of a
        # SHA1 hash; if it doesn't, no point trying to look it up in
        # the database.
        if SHA1_RE.search(activation_key):
            profile = RegistrationProfile.get_by_key_name("key_"+activation_key)
            if not profile:
                return False
            if not profile.activation_key_expired():
                user = profile.user
                user.is_active = True
                user.put()
                profile.activation_key = RegistrationProfile.ACTIVATED
                profile.put()
                return user
        return False
    
    def create_inactive_user(self, username, password, email, domain_override="", 
                             send_email=True, from_email=None):
        """
        Create a new, inactive ``User``, generate a
        ``RegistrationProfile`` and email its activation key to the
        ``User``, returning the new ``User``.        
        """
        # prepend "key_" to the key_name, because key_names can't start with numbers
        new_user = User(username=username, key_name="key_"+username.lower(),
            email=email, is_active=False)
        new_user.set_password(password)
        new_user.put()
        
        registration_profile = self.create_profile(new_user)
        
        if send_email:
            from django.core.mail import send_mail
            current_site = domain_override
            subject = _("Activation email for ") + current_site
            message = render_to_string('userprofile/activation_email.txt',
                                       { 'activation_key': registration_profile.activation_key,
                                         'expiration_days': settings.ACCOUNT_ACTIVATION_DAYS,
                                         'site': current_site })
            if not from_email:
                from_email = settings.DEFAULT_FROM_EMAIL
            send_mail(subject, message, from_email, [new_user.email])
        return new_user
    
    def create_profile(self, user):
        """
        The activation key for the ``RegistrationProfile`` will be a
        SHA1 hash, generated from a combination of the ``User``'s
        username and a random salt.        
        """
        salt = sha.new(str(random.random())).hexdigest()[:5]
        activation_key = sha.new(salt+user.username).hexdigest()
#       prepend "key_" to the key_name, because key_names can't start with numbers     
        registrationprofile = RegistrationProfile(user=user, activation_key=activation_key, key_name="key_"+activation_key)
        registrationprofile.put()
        self.delete_expired_users()
        return registrationprofile
        
    def delete_expired_users(self):
        for profile in RegistrationProfile.all():
            if profile.activation_key_expired():
                user = profile.user
                if not user.is_active:
                    user.delete()
                    profile.delete()

class RegistrationProfile(db.Model):
    """ 
    Stores an activation key for use during
    user account registration 
    """
    ACTIVATED = u"ALREADY_ACTIVATED"
    
    user = db.ReferenceProperty(User, verbose_name=_('user'))
    activation_key = db.StringProperty(_('activation key'))
    objects = RegistrationManager()
    
    def __unicode__(self):
        return u"Registration information for %s" % self.user
    
    def activation_key_expired(self):
        """
        Determine whether this ``RegistrationProfile``'s activation
        key has expired, returning a boolean -- ``True`` if the key
        has expired.
        
        Key expiration is determined by a two-step process:
        
        1. If the user has already activated, the key will have been
           reset to the string constant ``ACTIVATED``. Re-activating
           is not permitted, and so this method returns ``True`` in
           this case.

        2. Otherwise, the date the user signed up is incremented by
           the number of days specified in the setting
           ``ACCOUNT_ACTIVATION_DAYS`` (which should be the number of
           days after signup during which a user is allowed to
           activate their account); if the result is less than or
           equal to the current date, the key has expired and this
           method returns ``True``.
        
        """
        expiration_date = timedelta(days=settings.ACCOUNT_ACTIVATION_DAYS)
        return self.activation_key == RegistrationProfile.ACTIVATED or \
               (self.user.date_joined + expiration_date <= datetime.now())
    activation_key_expired.boolean = True

templates/userprofile/activate_complete.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}
	{% trans "Activation successful" %}
{% endblock %}

{% block content %}

<h1>{% trans "Activation successful" %}</h1>
<p>{% trans "Congratulations" %}. {% trans "Your account has been created successfully" %}.</p>

{% endblock content %}

templates/userprofile/base_profile.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<p id="submenu" class="clearfix">
	<a href="{% url user_settings %}">{% trans "Main" %}</a>
	<a href="{% url user_link %}">{% trans "Links" %}</a>
	<a href="{% url user_avatar %}">{% trans "Avatar" %}</a> 
	<a href="{% url user_theme %}">{% trans "Theme" %}</a>
	<a href="{% url user_pass_change %}">{% trans "Password" %}</a>
</p>
{% block user_content %}{% endblock %}
{% endblock %}

templates/userprofile/getpassword.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block content %}

<h1>{% trans "Password reset" %}</h1>
      
<p>{% trans "Please tell us the email used in the registration" %}.</p>
	
<form id='passform' action='.' method='post' class="content">

	<table class="formtable" cellpadding="0" cellspacing="0">
		{{ form.as_table }}

		<tr><th></th>
		<td><input type="submit" value="{% trans "Submit" %}" alt="{% trans "Submit" %}" /></td>
		</tr>
	</table>
</form>
    
{% endblock %}

templates/userprofile/login.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Login" %}{% endblock %}
{% block js %}<script type="text/javascript">
    /* <![CDATA[ */
        $(function() {$('#id_username').focus();});
    /* ]]> */
</script>
{% endblock %}
{% block content %}

<h1>{% trans "Login" %}</h1>

<form action='.' method='post' class="content">

<fieldset class="last">

<p>{% trans "Login with your username and password" %}.</p>

<table class="formtable" cellpadding="0" cellspacing="0">
	{{ form.as_table }}
	<tr><th></th>
	<td><input type="submit" value="{% trans "Login" %}" alt="{% trans "Login" %}" /></td>
	</tr>
</table>

</form>

<p><a href="{% url password_reset %}">{% trans "Lost the password?" %}</a> {% trans "or" %} <a href="{% url register %}">{% trans "want to join?" %}</a></span></p>

{% endblock %}

templates/userprofile/login_required.html
{% extends "base.html" %}

{% load i18n %}
{% block title %}{% trans "Login required" %}{% endblock %}

{% block user_content %}

<h1>{% trans "Login required" %}</h1>
<p>{% trans "You need to be logged to perform this operation" %}
.{% trans "If you have an account you can login" %} <a href="{% url login %}">{% trans "here" %}</a>. {% trans "Or you can join the site" %} <a href="{% url register %}">{% trans "here" %}</a>.</p>

{% endblock %}

templates/userprofile/password_change_done.html
{% extends "userprofile/base_profile.html" %}
{% block title %}Password Changed{% endblock %}

{% block user_content %}

<h1>Password Changed</h1>

  <p>Password changed successfully. </p>

{% endblock %}

templates/userprofile/password_change_form.html
{% extends "userprofile/base_profile.html" %}

{% load i18n %}

{% block title %}Password Change{% endblock %}

{% block user_content %}

<h1>Password Change</h1>

<form action='.' method='post'>
	<table class="formtable" cellpadding="0" cellspacing="0">
		{{ form.as_table }}
	<tr><th></th>
		<td><input type="submit" value="{% trans "Change" %}" alt="{% trans "Change image" %}" /></td>
	</tr>
</table>
</form>

{% endblock %}

templates/userprofile/password_reset_done.html
{% extends "base.html" %}

{% block title %}Password reset{% endblock %}

{% block content %}

<h1>Password reset</h1>

<p>You wil receive an email with instructions for resetting your password. Please check your inbox.</p>

{% endblock %}

templates/userprofile/password_reset_email.html
Hi!
In order to reset your password please visit the following link:

{{ protocol }}://{{ domain }}/account/confirm/{{ user.id }}/{{ token }}/

If you did not request a password reset, please ignore this email, nothing will be changed in your account.

Thanks,
Support team

templates/userprofile/register.html
{% extends "base.html" %}

{% block title %}New user{% endblock %}

{% block content %}

<h1>New user</h1>

<form action='.' method='post' class="content">

<p>Please choose your username and password</p>
	<table class="formtable" cellpadding="0" cellspacing="0">
		{{ form.as_table }}
	<tr><th></th>
	<td><input type="submit" value="Submit" alt="Submit request" /></td>
	</tr>
</table>
</form>

{% endblock %}

templates/userprofile/theme.html
{% extends "userprofile/base_profile.html" %}

{% load i18n %}

{% block title %}{% trans "Theme Settings" %}{% endblock %}

{% block user_content %}

<h1>{% trans "Theme Settings" %}</h1>

{% if msg %}<p class="msgbox hilite">{{ msg }}.</p>{% endif %}

<p>{% trans "Personalize your walkon display. Choose a theme or customize the background and colors." %}</p>

<table id="themes">
	<tr>
		<td><a href="{% url user_theme %}?theme=default"><img src="/img/small_default.jpg"></a></td>
		{% for theme in themes %}
		<td><a href="{% url user_theme %}?theme={{ theme.name }}"><img src="{{ theme.thumbnail_path }}"
			{% ifequal theme user.theme %} class="selectedimage"{% endifequal %}></a></td>
		{% endfor %}
	</tr>
</table>

<form action="." method="post" enctype="multipart/form-data">

	<table class="formtable" cellpadding="0" cellspacing="0">	
		{{ form.as_table }}
		<tr><th></th>
			<td><input type="submit" value="{% trans "Save" %}" alt="{% trans "Save data" %}" /></td>
		</tr>
	</table>
</form>

{% endblock %}

templates/userprofile/user_admin.html
{% extends "userprofile/base_profile.html" %}

{% load i18n %}
{% load paginator %}

{% block title %}{% trans "Manage Users" %}{% endblock %}

{% block user_content %}

<h1>{% trans "Manage Users" %}</h1>
	
	<table class="mainlist">
		<tr><th>{% trans "Username" %}</th>
			<th>{% trans "Email" %}</th>
			<th>{% trans "Staff" %}</th>
		</tr>
	{% for u in users %}
		<tr><td><a href="{% url user_admin_detail u.username %}">{{ u.username }}</a></td>
			<td><a href="{% url user_admin_detail u.username %}">{{ u.email }}</a></td>
			<td><input type="checkbox" {% if u.is_staff %}checked{% endif%} disabled></td>
		</tr>
		
	{% endfor %}
	</table>
	{% pagination 5 %}

{% endblock %}

templates/userprofile/user_admin_detail.html
{% extends "userprofile/base_profile.html" %}

{% load i18n %}

{% block title %}{% trans "Change user details" %}{% endblock %}

{% block user_content %}

<h1>{% trans "Change user details" %}</h1>

<p>{% trans "Details for" %} {{ user.username }} ({{ user.email }})</p>
		
<form action='{% url user_admin_detail user.username %}' method='post' class="content">
	<table class="formtable" cellpadding="0" cellspacing="0">
		{{ form.as_table }}
		<tr><th></th>
			<td><input type="submit" value="{% trans "Change" %}" alt="{% trans "Change user details" %}" /></td>
		</tr>
	</table>
</form>

{% endblock %}

templates/userprofile/user_link.html
{% extends "userprofile/base_profile.html" %}

{% load i18n %}

{% block title %}{% trans "Add profile links" %}{% endblock %}

{% block user_content %}

<h1>{% trans "Profile Links" %}</h1>

{% if msg %}<p class="msgbox hilite">{{ msg }}.</p>{% endif %}

<p>{% trans "Add or remove profile links." %}</p>

<form action="." method="post">

	<table class="formtable" cellpadding="0" cellspacing="0">
		{% if user.link_set.get %}
		<tr><th><label for="id_link">{% trans "Links" %}:</label></th><td>
			<ul id="link-list-manage">
				{% for link in user.link_set %}
				<li>
					<a href="{% url user_linkremove link_key=link.key %}">
						<img src="/img/icon_deletelink.gif" /></a>
					<a class="link-name" href="{{ link.url }}">{{ link.name }}</a>
				</li>
				{% endfor %}
			</ul>
		</td><td class="info">
			{% trans "Click on the cross to remove the link." %}
		</td></tr>
		{% endif %}
			
		{{ form.as_table }}

		<tr><th></th>
			<td><input type="submit" value="{% trans "Add" %}" alt="{% trans "Add link" %}" /></td>
		</tr>
	</table>
</form>

{% endblock %}