urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from userprofile.forms import PasswordResetForm

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('userprofile.views',
    url(r'^account/img/(?P<userkey>[.a-zA-Z0-9_\-]+)/(?P<filename>.*)$', 'avatar_image', name='avatar_image'),
    url(r'^account/conf/$', 'user_settings', name='user_settings'),
    url(r'^account/avatar/$', 'user_avatar', name='user_avatar'),
    url(r'^account/theme/$', 'user_theme', name='user_theme'),
    url(r'^account/bg/(?P<userkey>[.a-zA-Z0-9_\-]+)/(?P<filename>.*)$', 'theme_image', name='theme_image'),
    url(r'^account/links/$', 'user_link', name='user_link'),
    url(r'^account/link/(?P<link_key>[.a-zA-Z0-9_\-]+)/remove/$', 'link_remove', name='user_linkremove'),
    url(r'^account/admin/$', 'user_admin', name='user_admin'),
    url(r'^account/admin/(?P<username>[.a-zA-Z0-9_@\-]+)/$', 'user_admin_detail', name='user_admin_detail'),
)

urlpatterns += patterns('',
    url(r'^account/login/$', 'userprofile.views.email_login', {'template_name': 'userprofile/login.html'}, name='login'),
    url(r'^account/logout/$', 'userprofile.views.do_logout', name='logout'),
    url(r'^account/register/$', 'userprofile.views.register_inactive_user', name='register'),
    url(r'^account/register/complete/$', direct_to_template, {'template': 'userprofile/register_complete.html'}, name='register_complete'),
    url(r'^account/activate/complete/$', 'userprofile.views.activate_complete', name='register_activate_complete'),
    url(r'^account/activate/(?P<activation_key>\w+)/$', 'userprofile.views.activate', name='register_activate'),
    url(r'^account/password/change/$', 'django.contrib.auth.views.password_change', 
        {'template_name':'userprofile/password_change_form.html'}, name='user_pass_change'),
    url(r'^account/password/change/complete/$', 'django.contrib.auth.views.password_change_done', 
        {'template_name':'userprofile/password_change_done.html'}, name='user_pass_change_done'),
    url(r'^account/recover/$', 'django.contrib.auth.views.password_reset', 
            {'template_name':'userprofile/getpassword.html', 'email_template_name':'userprofile/password_reset_email.html',
             'password_reset_form':PasswordResetForm}, name='password_reset'),
    url(r'^account/recover/complete/$', 'django.contrib.auth.views.password_reset_done', 
            {'template_name': 'userprofile/password_reset_done.html'}, name='reset_done'),
    url(r'^account/confirm/(?P<uidb36>.+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', 
            {'template_name': 'userprofile/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^account/confirm/complete/$', 'django.contrib.auth.views.password_reset_complete', 
            {'template_name': 'userprofile/password_reset_complete.html'}, name='password_reset_last'),
)

urlpatterns += patterns('walkon.views',
    url(r'^on/(?P<username>[.a-zA-Z0-9_@\-]+)/$','userpage', name='userpage'),
    url(r'^cfg/$','global_config', name='cfg_main'),
    url(r'^cfg/goal/$','goal', name='cfg_goal'),
    url(r'^cfg/activities/$','activities', name='cfg_activities'),
)

#Initializations 

urlpatterns += patterns('walkon.views',
    url(r'^getsteptable/$', 'get_step_table', name='step_table_ajax'),
    url(r'^getfullstepform/$', 'get_full_step_form', name='full_step_form_ajax'),
    url(r'^reports/$', 'reports', name='reports'),
    url(r'^reports/fullresults/$', 'full_results', name='full_results'),
    url(r'^reports/map/$', 'reports', name='report_map'),
    url(r'^reports/activities/$', 'reports_activities', name='report_activities'),
    url(r'^reports/benchmark/$', 'reports_benchmark', name='report_benchmark'),
    url(r'^reports/projections/$', 'reports_projections', name='report_projections'),
    url(r'^reports/rankings/$', 'reports_rankings', name='report_rankings'),
    url(r'^reports/steps/$', 'reports_steps', name='report_steps'),
    url(r'^bg/(?P<filename>.*)$', 'global_theme_image', name='global_theme_image'),
    (r'^updatestats$', 'update_user_stats'),
    (r'^cropstats$', 'crop_stats'),
    (r'^clearstats$', 'clear_stats'),
    (r'^clearsteps$', 'clear_steps'),
    (r'^fillconfig$', 'create_config'),
    (r'^init$', 'initialization'),    
    url(r'^$', 'index', name="index"),
    (r'^admin/(.*)', admin.site.root),
)

walkon/forms.py
# -*- coding: utf-8 -*-
from datetime import date
import time
import logging
from google.appengine.ext.db import GeoPt, GqlQuery
from django import forms
from django.utils.translation import ugettext as _
from django.forms.fields import EMPTY_VALUES
import settings
from models import Goal
from walkon.removable_file_field import RemovableFileFormField

class DateForm(forms.Form):
    date = forms.DateField(label=_("Date"), help_text=_("Date format (yyyy-mm-dd)"))
    show_cal = forms.IntegerField(widget=forms.HiddenInput(), required=False, initial=1)

def validate_int(value):
        """
        Validates that int() can be called on the input. Returns the result
        of int(). Returns None for empty values.
        """
        if value in EMPTY_VALUES:
            return None
        try:
            value = int(str(value))
        except (ValueError, TypeError):
            raise forms.ValidationError(_(u'Enter a whole number.'))
        return value

def validate_date(value, required=False):
    """
    Validates that the input can be converted to a date. Returns a Python
    datetime.date object.
    """
    if value in EMPTY_VALUES:
        if not required:
            return None
    elif isinstance(value, date):
        return value
    else:
        try:
            return date(*time.strptime(value, '%Y-%m-%d')[:3])
        except ValueError:
            pass
    raise forms.ValidationError(_(u'Enter a valid date.'))

class StepForm:
    """My own StepForm.
    
    The problem is that this form is so dynamic that we can never be sure of what the state was when it was
    submitted, so I need a general validation that is independent of the current fields.
    """
    def __init__(self, postdata=None, activities=[], initial=None):
        self.errors = []
        self.steps = self.date_hidden = None
        if initial:
            self.validate(initial)
        if postdata:
            self.validate(postdata, posted=True)
        self.activities = [dict(form_id='act' + str(act.key()), label=_(act.name), help_text=act.steps_min) for act in activities]
        
    def validate(self, initial, posted=False):
        """posted = False - validate that data is valid for the type of field; True - global logic validation"""
        # steps
        self.errors = []
        try:
            self.steps = validate_int(initial.get('steps', None))
        except forms.ValidationError, e:
            self.errors.extend(e.messages)
        # date-hidden
        try:
            self.date_hidden = validate_date(initial.get('date_hidden', None), required=True)
            if posted:
                if self.date_hidden > date.today():
                    raise forms.ValidationError(_("Can't input values in a future date."))
                goal = Goal.all().get()
                if self.date_hidden < goal.start_date:
                    raise forms.ValidationError(_("Can't input values before the start date."))
                if self.date_hidden > goal.end_date:
                    raise forms.ValidationError(_("Can't input values after the finish date."))
        except forms.ValidationError, e:
            self.errors.extend(e.messages)

        # activities
        try:
            self.activity_inputs = [ (name[3:], validate_int(value)) for name, value in initial.items() if value not in EMPTY_VALUES and name.startswith('act') ]
        except forms.ValidationError:
            self.errors.append(_("Please enter a valid duration for all activities."))
        # validar estes valores apenas se não houver já erros
        if posted and not self.errors and not self.steps and not self.activity_inputs:
            self.errors.append(_("Please enter something for at least one field."))
            
    def is_valid(self):
        return self.errors == []

class ActivityForm(forms.Form):
    activity = forms.CharField(label=_("Activity label"))
    steps = forms.IntegerField(label=_("Steps"),
                help_text=_("Equivalent number of steps for each minute of activity"))
    
    def clean_activity(self):
        name=self.cleaned_data['activity']
        query = GqlQuery("SELECT * FROM Activity WHERE name=:1", name)
        if query.count() > 0:
            raise forms.ValidationError(_("Activity already exists"))
        return self.cleaned_data['activity']

class ConfigForm(forms.Form):
    from_email = forms.EmailField(label=_("Email"), required=False, 
                 help_text=_("This email is the sender for messages sent to users. The email must also be in the list of appengine emails."))
    maps_key = forms.CharField(label=_("Google Maps Key"), required=False,
                help_text=_("With a valid key for your domain you can define the geographical coordinates of starting and finish point, the distance and path using google maps. You will also be able to see the user's current position and progress in a nice map."))
    allowed_domains = forms.CharField(label=_("Allowed domains"), required=False,  widget=forms.Textarea(),
                help_text=_("Comma separated list of domains accepted for new user registration (for example: mydomain.com, myotherdomain.com)"))
    bg_color = forms.CharField(label='Background color', required=False)
    bg_image = RemovableFileFormField(label='Background image', required=False,
                help_text=_("Maximum file size of %s kb" % int(settings.MAX_UPLOAD_SIZE / 1024)))
    bg_repeat = forms.BooleanField(label='Image repeat', required=False)
    link_color = forms.CharField(label='Link color', required=False)
    site_color1 = forms.CharField(label='Site color 1', required=False)
    site_color2 = forms.CharField(label='Site color 2', required=False)

    def __init__(self, *args, **kwargs):
        filename = ''
        if kwargs.has_key('initial') and kwargs['initial'].has_key('filename'):
            filename = kwargs['initial']['filename']
        logging.debug("FILENAME: " + str(filename))
        path = ''
        if kwargs.has_key('initial') and kwargs['initial'].has_key('path'):
            path = kwargs['initial']['path']
        logging.debug(path)
        super(ConfigForm, self).__init__(*args, **kwargs)
        self.fields['bg_image'].widget.set_filename(filename)
        self.fields['bg_image'].widget.set_path(path)
    
    def clean_bg_image(self):
        newfile = self.cleaned_data['bg_image'][0]
        if newfile and hasattr(settings, 'MAX_UPLOAD_SIZE') and newfile.size > settings.MAX_UPLOAD_SIZE:
            max_kbytes = int(settings.MAX_UPLOAD_SIZE / 1024)
            raise forms.ValidationError(_("Please use a file with size under %s kb.") % max_kbytes)
        return self.cleaned_data['bg_image']

class GoalForm(forms.Form):
    start = forms.CharField(label=_("Departure Town"))
    finish = forms.CharField(label=_("Arrival Town"))
    start_date = forms.DateField(label=_("Departure Date"), help_text=_("Date format (yyyy-mm-dd)"))
    end_date = forms.DateField(label=_("Arrival Date"), help_text=_("Date format (yyyy-mm-dd)"))
    total_distance = forms.FloatField(label=_("Total distance (km)"), min_value=0, max_value=999999)
    start_geo = forms.CharField(widget=forms.HiddenInput(), required=False)
    finish_geo = forms.CharField(widget=forms.HiddenInput(), required=False)
    directions = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    #MORE CHECKS:
    #end date > start date
    
    def clean_end_date(self):
        if self.cleaned_data['end_date'] and self.cleaned_data['start_date']:
            if self.cleaned_data['start_date'] > self.cleaned_data['end_date']:
                raise forms.ValidationError(_("Arrival date must be after the departure date"))
        return self.cleaned_data['end_date']
    
    def map_geo(self, value):
        try:
            lat, lon = map(float,value.split(','))
            return GeoPt(lat, lon)
        except ValueError:
            return None
            
    def clean_start_geo(self):
        return self.map_geo(self.cleaned_data['start_geo'])
    
    def clean_finish_geo(self):
        return self.map_geo(self.cleaned_data['finish_geo'])

templates/activities.html
{% extends "base_admin.html" %}

{% load i18n %}

{% block title %}{% trans "Activities" %}{% endblock %}
{% block js %}
<script type="text/javascript" src="/js/goal.js"></script>
{% endblock %}

{% block admin_content %}
    <h1>{% trans "Activities" %}</h1>

	{% if msg %}<p class="success hilite">{{msg}}</p>{% endif %}

	<table class="medium" cellpadding="0" cellspacing="0">
		<tr><th>{% trans "Description" %}</th><th>{% trans "Steps/Minute" %}</th></tr>
		{% for act in activities %}
        	<tr><td>{{act.name}}</td><td>{{act.steps_min}}</td><td>
				<form action="." method="POST">
					<input type="submit"  name="del{{act.key}}" value="{% trans "Delete" %}"/></form>
				</td><td></tr>
        {% endfor %}
	</table>
    
	<form action="." method="POST">
		<legend>{% trans "Add a new activity to the list" %}.</legend>
		<table class="formtable" cellpadding="0" cellspacing="0">
			{{ form.as_table }}
		</table>
		
		<table class="formsubmit" cellpadding="0" cellspacing="0">
			<tr><th></th>
			<td><input type="submit" value="{% trans "Add" %}" alt="{% trans "Add activity" %}" /></td>
			<td></td></tr>
		</table>
	</form>
{% endblock %}

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
    dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}"
    xml:lang="{% firstof LANGUAGE_CODE 'en' %}"
    lang="{% firstof LANGUAGE_CODE 'en' %}">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>{% block title %}{% endblock %} - Walk On</title>
	<link rel="stylesheet" href="/css/alt.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="/css/tabs.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="/css/main.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="/css/datepicker.css" type="text/css" media="all"/>

	<style type="text/css">
	{% if member %}
		body {background: {{ member.get_bgcolor }} {% if member.get_bgimage %}url({{ member.get_bgimage }}) fixed {% if member.get_bgrepeat %}repeat{% endif %} top left{% endif %}; }
		a { color: {{ member.get_linkcolor }}; } 
		th { background:{{ member.get_sitecolor1 }}; }
		tr.even td { background:{{ member.get_sitecolor2 }}; }
	{% else %}
		{% if user.is_authenticated %}
			body {background: {{ user.get_bgcolor }} {% if user.get_bgimage %}url({{ user.get_bgimage }}) fixed {% if user.get_bgrepeat %}repeat{% endif %} top left{% endif %}; }
			a { color: {{ user.get_linkcolor }}; } 
			th { background:{{ user.get_sitecolor1 }}; }
			tr.even td { background:{{ user.get_sitecolor2 }}; }		
		{% else %}
			{% if global_config.has_theme %}
        		body {background: {{ global_config.get_bgcolor }} {% if global_config.get_bgimage %}url({{ global_config.get_bgimage }}) fixed {% if global_config.get_bgrepeat %}repeat{% endif %} top left{% endif %}; }
				a { color: {{ global_config.get_linkcolor }}; } 
				th { background:{{ global_config.get_sitecolor1 }}; }
				tr.even td { background:{{ global_config.get_sitecolor2 }}; }
			{% endif %}
		{% endif %}
	{% endif %}	
	</style>

    <script type="text/javascript" src="/js/jquery-1.3.1.min.js"></script>
    <script type="text/javascript" src="/js/jquery.validate.pack.js" charset="ISO-8859-1"></script>
	<script type="text/javascript" src="/js/jquery.color.js"></script>
    <script type="text/javascript" src="/js/main.js"></script>
    <script type="text/javascript" src="/js/datepicker.js"></script>

    {% block css %}{% endblock %}
    {% block js %}{% endblock %}
    {% block extra-head %}{% endblock %}
  </head>

  <body {% block onload %}{% endblock %}>

	<div id="container">
		<div id="header" class="clearfix">
			<ul id="nav">
				{% if user.is_authenticated %}
				<li>Welcome <a href="{% url userpage username=user.username %}">{{ user.username }}</a></li>
				{% endif %}
				<li><a href="{% url index %}" rel="home">Home</a></li>
				<li><a href="{% url reports %}">Statistics</a></li>
				{% if user.is_authenticated %}
				<li><a href="{% url user_settings %}">Settings</a></li>
				<li><a href="{% url logout %}">Logout</a></li>
				{% else %}	
				<li><a href="{% url login %}">Login</a></li>
		        <li><a href="{% url register %}">Register</a></li>
				{% endif %}
				{% if user.is_superuser %}
				<li><a href="{% url cfg_main %}">Admin</a></li>
				{% endif %}
			</ul>

            <h1>Walk On</h1>
            {% if goal %}<p class="bottom">from {{ goal.start }} on {{ goal.start_date }} to {{ goal.finish }} arriving on {{ goal.end_date }}. Total distance: {{ goal.total_distance|floatformat:0 }} km.</p>
            {% else %}<p class="bottom loud">You haven't defined the objective yet.</p>{% endif %}
        </div>
    <!--<div id="content" class="column">
      {% block content-header %}
        {% if error %}<div class="error">{{ error }}</div>{% endif %}
        {% if info %}<div class="info">{{ info }}</div>{% endif %}
        {% if messages %}
          {% for message in messages %}
            <div class="info">{{ message }}</div>
          {% endfor %}
        {% endif %}
      {% endblock %}
      
    </div>-->

	{% block widget %}{% endblock %}

	{% block messages %}{% endblock %}

	<div id="content">
	  {% block content %}{% endblock %}
	</div>

	{% block sidebar %}
	{% endblock %}

	<br style="clear:both;" />

	<div id="footer">
		<p> &copy; 2010 Cognitiva</p>
	</div>

    </div>
  </body>
</html>

templates/full_table.html
{% extends "reports.html" %}
{% block title %}Walk On - Report Table{% endblock %}
{% block onload %}{% endblock %}
{% block report %}
        <div class="span-12 last">
            {% with "true" as in_stats %}
            {% include "inc_personal_ranking.html" %}
            {% endwith %}
        </div>
{% endblock %}

templates/globalconfig.html
{% extends "base_admin.html" %}
{% load i18n %}

{% load i18n %}

{% block title %}Configuration{% endblock %}

{% block admin_content %}
<h1>Global configuration</h1>

<form action="." method="post" id="config-form" enctype="multipart/form-data">

{% if save %}<p class="success hilite">{% trans "Your changes have been saved" %}</p>{% endif %}

<fieldset class="last">
<legend>Global site configurations.</legend>

<table class="formtable" cellpadding="0" cellspacing="0">
	{{ form.as_table }}
</table>
</fieldset>

<table class="formsubmit" cellpadding="0" cellspacing="0">
	<tr>
	<th></th>
	<td><input type="submit" value="Change" alt="Change" /></td>
	<td class="info"></td>
	</tr>
</table>

Available themes: 

<table id="themes">
	<tr>
		<td><a href="{% url cfg_main %}?theme=default"><img src="/img/small_default.jpg"></a></td>
		{% for theme in themes %}
		<td><a href="{% url cfg_main %}?theme={{ theme.name }}"><img src="{{ theme.thumbnail_path }}"
			{% ifequal theme globalconfig.theme %} class="selectedimage"{% endifequal %}></a></td>
		{% endfor %}
	</tr>
</table>

</form>
{% endblock %}

templates/goal.html
{% extends "base_admin.html" %}

{% load i18n %}

{% block title %}{% trans "Objective" %}{% endblock %}
{% block js %}
<script type="text/javascript" src="/js/goal.js"></script>
{% if config.maps_key %}
<script type="text/javascript" src="/js/PolylineEncoder.js"></script>
<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key={{ config.maps_key }}&amp;sensor=false"
      type="text/javascript"></script>
    <script type="text/javascript">

    //<![CDATA[
    var point1=point2=marker1=marker2=null;
    var dirobj=encodedPolyline=null;
    var polylineEncoder = new PolylineEncoder();
    function load() {
      if (GBrowserIsCompatible()) {
        var div = document.getElementById("map");
        var map = new GMap2(div);
        var customUI = map.getDefaultUI();
        customUI.controls.maptypecontrol = false;
        map.setUI(customUI);
        var bounds = new GLatLngBounds;
        var start_geo = $("#id_start_geo").val();
        var finish_geo = $("#id_finish_geo").val();
        if (start_geo != '')
        {
            var start_geo_array = start_geo.split(',');
            map.setCenter(new GLatLng(parseFloat(start_geo_array[0]),parseFloat(start_geo_array[1])), 9);
            point1 = new GLatLng(parseFloat(start_geo_array[0]),parseFloat(start_geo_array[1]));
            marker1 = new GMarker(point1);
            map.addOverlay(marker1);
            bounds.extend(point1);
        }
        if (finish_geo != '')
        {
            var finish_geo_array = finish_geo.split(',');
            point2 = new GLatLng(parseFloat(finish_geo_array[0]),parseFloat(finish_geo_array[1]));
            marker2 = new GMarker(point2);
            map.addOverlay(marker2);
            bounds.extend(point2);
        }
        if (start_geo != '' || finish_geo != '')
        {
            map.setZoom(map.getBoundsZoomLevel(bounds));
            map.setCenter(bounds.getCenter());
        }
        else
        {
            map.setCenter(new GLatLng(0,0), 3);
        }
        if ($("#id_directions").val() != '')
        {
            dir_line = {
                color: "#FF0000",
                weight: 10,
                points: $("#id_directions").val(),
                levels: "BBB",
                zoomFactor: 32,
                numLevels: 4
            }
            encodedPolyline = new GPolyline.fromEncoded(dir_line);
            map.addOverlay(encodedPolyline);
        }
        GEvent.addListener(map, "click", function(marker, point) {
            if (marker)
            {
                map.removeOverlay(marker);
                if (dirobj != null)
                    dirobj.clear();
                if (encodedPolyline != null)
                    map.removeOverlay(encodedPolyline);
                $("#id_total_distance").val('');
                $("#id_directions").val('');
                if (marker.getLatLng() == point2)
                {
                    point2 = null;
                    $("#id_finish_geo").val('');
                    marker2 = null;
                }
                else if (marker.getLatLng() == point1)
                {
                    if (marker2 != null) map.removeOverlay(marker2);
                    point1 = point2 = null;
                    marker1 = marker2 = null;
                    $("#id_start_geo").val('');
                    $("#id_finish_geo").val('')
                }
            }
            else
            {
                if (point1 == null)
                {
                    point1 = point;
                    $("#id_start_geo").val(point1.lat() + "," + point1.lng())
                    marker1 = new GMarker(point);
                    map.addOverlay(marker1);
                }
                else if (point2 == null)
                {
                    point2 = point;
                    marker2 = new GMarker(point);
                    map.addOverlay(marker2);
                    $("#id_finish_geo").val(point2.lat() + "," + point2.lng())
                    dirobj = new GDirections();
                    var ar = new Array(point1, point2);
                    dirobj.loadFromWaypoints(ar, {getPolyline:true});
                    GEvent.addListener(dirobj, "load", function(x) {
                        var distance = dirobj.getDistance().meters / 1000.;
                        var points = [];
                        for (var i=0; i< dirobj.getPolyline().getVertexCount(); i++) {
                            points[i] = dirobj.getPolyline().getVertex(i);
                        }
                        polyline = polylineEncoder.dpEncode(points);
                        $("#id_total_distance").val(distance.toFixed(2));
                        $("#id_directions").val(polyline.encodedPoints);
                        encodedPolyline = dirobj.getPolyline();
                        map.addOverlay(encodedPolyline);
                    });
                }
            }
        });
//         var dir = new GDirections(map, dir);
//         var ar = new Array(point1, point2);
//         dir.loadFromWaypoints(ar);
//         GEvent.addListener(dir, "addoverlay", function(x) {
//             map.openInfoWindowHtml(
//             point2,
//             dir.getDistance().html);
//         });

      }
    }

$(document).ready(load);
$(document.body).unload(GUnload);
//]]>
</script>
{% endif %}
{% endblock %}
{% block onload %}{% endblock %}

{% block admin_content %}

<h1>{% trans "Objective" %}</h1>

{% if save %}
<p class="success hilite">{% trans "Your changes have been saved" %}.</p>
{% endif %}

<form action="." method="post" id="goal-form">
	{% if info %}
	<legend><strong>{% trans "The competiton has started" %}!</strong><br/>{% trans "Please take care when changing the objective after the starting date - if users have entered any data it may cause inconsistencies" %}.</legend>
	{% else %}
	<legend>{% trans "Please define the objective" %}.</legend>
	{% endif %}
	
	<table class="formtable" cellpadding="0" cellspacing="0">
		{{ form.as_table }}
	</table>

	{% if config.maps_key %}
	<div id="map"></div>
	{% endif %}
	
	<table class="formsubmit" cellpadding="0" cellspacing="0">
		<tr>
		<th></th>
		<td><input type="submit" value="{% if goal %}{% trans "Change" %}{% else %}{% trans "Create" %}{% endif %}" alt="{% if goal %}{% trans "Change" %}{% else %}{% trans "Create" %}{% endif %}" /></td>
		<td class="info"></td>
		</tr>
	</table>
</form>	

{% endblock %}

templates/inc_cumulative_graph.html
                <p id="g1" class="report-graph">Cumulative distance:<br/>
                <img src="http://chart.apis.google.com/chart?chs=500x300&amp;chd=t:{{stats_line.me|join:","}}|{{stats_line.top|join:","}}|{{stats_line.avg|join:","}}&amp;chds=0,{{stats_line.top_max}}&amp;cht=lc&amp;chxt=x,y&amp;chxl=0:|{{startdate.isoformat}}|{{thisdate.isoformat}}&amp;chxr=1,0,{{stats_line.top_max}}&amp;chdl={{whoami.get_full_name|urlencode}}|Leader|Average&amp;chco=FF0000,00FF00,0000FF" alt="Cumulative distance"/>
                </p>

templates/inc_poswidget.html
<div id="poswidget">
	
<div id="head-graph" class="box" style="position: relative">
    <div style="margin: 0px 25px; width: 750px; height:50px; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 1px solid black"></div>
    <p style="margin: 0; text-align: right;"><span style="float: left">{{goal.start}}</span>{{goal.finish}}</p>
    <div style="width: 25px; height: 55px; border: none; position: absolute; top:5px; left: {{summary.1.1}}px; text-align: center; line-height: 15px">Me<img  src="/img/walk2.png" alt="Me"/></div>
    <div style="width: 25px; height: 55px; border: none; position: absolute; top:5px; left: {{summary.0.1}}px; text-align: center; line-height: 15px">Leader<img  src="/img/walk2-green.png" alt="Leader"/></div>
    <div style="width: 25px; height: 55px; border: none; position: absolute; top:5px; left: {{summary.2.1}}px; text-align: center; line-height: 15px">Avg<img  src="/img/walk2-yellow.png" alt="Average"/></div>
</div>

</div>

templates/nogoal.html
{% extends "base.html" %}
{% block title %}WalkOn{% endblock %}
{% block content %}
        <div id="title-head" class="box">
            <h3>Nowhere to walk</h3>
        </div>
        <div>
            Thanks for logging in, but you need to wait until the objective has been defined before you can start using this application :)
        </div>
{% endblock %}

templates/step_table.html
{% if entered_steps %}
                    {% for st in entered_steps %}
                        <tr><td>{{st.activity.name|default:"Counter"}}</td><td>{{st.steps}}</td><td>{{st.distance}}</td><td><input type="submit" name="del{{st.key}}" value="Delete"/></td></tr>
                    {% endfor %}
{% endif %}